### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

### ISSUE THREAD

**Issue by gabiudrescu** [theofidry/AliceDataFixtures#115]
Although fixed in master, shouldn't there be a new release of this bundle to allow users enjoy deprecation free usage?

**Comment by theofidry** [comment]
There's been a couple of non-trivial merge on master and I want to properly review it all before doing a release. So this will have to wait for a bit as I'm really short of time as of late
