### ISSUE TITLE
Cached PurgerLoader signature does not match parent signature

### ISSUE THREAD

**Issue by siemendev** [theofidry/AliceDataFixtures#116]
Somehow related to #43 I guess.

The PurgeLoader load() method signature differs from the parent method signature when cached, see hautelook/AliceBundle#462

**Comment by theofidry** [comment]
would it be possible to get a full trace of the error and/or a reproducer?

**Comment by siemendev** [comment]
Actually it seems that the underlaying system is the problem. Anyway: Implementing an own persistance layer for nelmio/alice works fine, so this works for me. I can't replicate this on a blank system so the failure seems to be on my side. Thank you anyway for the answer but I think it's not relevant for AliceDataFixtures.

**Comment by oenie** [comment]
I'm encountering this message now. This starts as soon as i try to do anything like clear my symfony cache.

**Comment by theofidry** [comment]
@oenie best way is to try to get a reproducer, e.g. setting up a new project with the same dependency versions as you are using and checking the result there. I can only do some guess work without a reproducer unfortunately

**Comment by oenie** [comment]
OK, we can leaves this closed. As @siemendev mentioned, it ws probably a package anomaly.
I had an old version of ocramius/proxy-manager , which i think was the culprit. 
Might be interesting to keep in mind in the future when this kind of error is being reported.
Thanks for the quick reply and sorry to 'reopen' a closed issue.
