### ISSUE TITLE
TreeBuilder::root() is deprecated since Symfony 4.3

### ISSUE THREAD

**Issue by jianzhong** [theofidry/AliceDataFixtures#123]
After installation of this package, when I run phpunit, I got this warning message:
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "fidry_alice_data_fixtures" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

**Comment by MLDMoritz** [comment]
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0!

**Comment by gharlan** [comment]
already fixed in https://github.com/theofidry/AliceDataFixtures/pull/112

**Comment by mpiot** [comment]
Hi, is there a date scheduled for tagging a new version ? Symfony 5.0 is coming (november) and this patch was merged more than 10 months ago :/

**Comment by theofidry** [comment]
Unless someone is willing to work on #108 I'm fine with tagging a new version but IMO the CI should be updated to be green on both PHP 7.3 and 7.4 before that.

**Comment by ro0NL** [comment]
friendly ping :)

**Comment by snebes** [comment]
Another friendly ping, especially with Symfony 5.0 released today

**Comment by theofidry** [comment]
As stated [here](https://github.com/theofidry/AliceDataFixtures/issues/123#issuecomment-545955388), I'm fine with tagging it but IMO the CI should be fixed first

**Comment by alexislefebvre** [comment]
> Unless someone is willing to work on #108 I'm fine with tagging a new version but IMO the CI should be updated to be green on both PHP 7.3 and 7.4 before that.

The CI is green after the merge of #128. Is it possible to publish a new release that fix the deprecation?

**Comment by theofidry** [comment]
Done: https://github.com/theofidry/AliceDataFixtures/releases/tag/v1.1.2
