### ISSUE TITLE
TypeError: Argument 1 passed to Doctrine\ODM\MongoDB\UnitOfWork::getParentAssociation()

### ISSUE THREAD

**Issue by cnizzardini** [theofidry/AliceDataFixtures#146]
We have a document `Product` with an embedded document `Rating`:

```php
    /**
     * @var collection Embedded Ratings
     *
     * @ODM\EmbedMany(targetDocument=Rating::class)
     * @Groups({"readItemSubRes"})
     */
    private $ratings;
```

And a fixture like this:

```yaml
App\Document\Product:
  product0: {
      "_id":100,
      "title":"The best product",
      "ratings":[{"_id":1,"rating":4,"comment":"good rating!","date":"2020-01-01"}]
    }
```

When running unit tests we encounter this: 

> 1) App\Tests\DataProvider\RatingDataProviderTest::testGetCollection
> TypeError: Argument 1 passed to Doctrine\ODM\MongoDB\UnitOfWork::getParentAssociation() must be an object, array given, called in /var/www/project/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php on line 2114
> 
> /var/www/project/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:317
> /var/www/project/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:2114
> /var/www/project/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1651
> /var/www/project/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1590
> /var/www/project/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:452
> /var/www/project/vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php:75
> /var/www/project/vendor/theofidry/alice-data-fixtures/src/Loader/PersisterLoader.php:92
> /var/www/project/vendor/theofidry/alice-data-fixtures/src/Loader/PurgerLoader.php:119
> /var/www/project/tests/DataProvider/RatingDataProviderTest.php:45

While adding an `ODM\Field(type="collection")` to the embedded document does work, but that breaks our production application in strange ways due to using Symfony API Platform.

Is there a way around this or is this a bug?

**Comment by theofidry** [comment]
I'm not familiar with MongoDB, but what's the type of `$ratings`? What is your setting `setRatings()` doing?

**Comment by cnizzardini** [comment]
It was this:

```
    public function setRating($ratings) : self
    {
        $this->ratings = $ratings;

        return $this;
    }
```

And I changed it to this to resolve it:

```
    public function setRatings(array $ratings) : self
    {
        foreach ($ratings as $rating) {
            if (!$rating instanceof Rating) {
                $rating = new Rating($cioRating);
            }
            $this->addRating($rating);
        }

        return $this;
    }
```

Had to adjust something in Rating constructor to, but that is okay, thanks for pointing me in the right direction. I owe you a beer (or sangria) next time I'm on Las Ramblas.
