### ISSUE TITLE
Minimum stability

### ISSUE THREAD

**Issue by Pizgu** [theofidry/AliceDataFixtures#15]
**composer require theofidry/alice-data-fixtures**

Result:
[InvalidArgumentException]                                                   
  Could not find package theofidry/alice-data-fixtures at any version for you  
  r minimum-stability (stable). Check the package spelling or your minimum-st  
  ability

**Comment by Pizgu** [comment]
Temporary solution to retrieve this package is to edit composer.json and insert into require (or require-dev) section with dev-master branch.

`"require-dev": {
        "doctrine/data-fixtures": "^1.2",
        "nelmio/alice": "dev-master",
        "hautelook/alice-bundle": "dev-master",
        "theofidry/alice-data-fixtures": "dev-master"
    },`

**Comment by theofidry** [comment]
you can also do `composer require "theofidry/alice-data-fixtures: ^1.0@dev"`. You are getting this error because there is not stable version yet, so you must ask a version yourself :)

**Comment by studiomado** [comment]
When I try to run any console command, I got this error:
`[ProxyManager\Exception\InvalidProxiedClassException]                                           
  Provided class "Fidry\AliceDataFixtures\Loader\PersisterLoader" is final and cannot be proxied`
What's the problem?

**Comment by theofidry** [comment]
Ah, looks like I missed an integration test for the lazyness (of services). The temporary fixes possible are:

- Copy/paste the .xml service declarations and remove the `lazy="true"` part
- Have a compiler pass to iterate through this library services and remove any `lazy=`"true"`

Sorry about that, I opened #16 for it.

**Comment by theofidry** [comment]
Another viable solution in the meantime is to also just not used ProxyManager*
