### ISSUE TITLE
Add support for ProxyManager

### ISSUE THREAD

**Issue by theofidry** [theofidry/AliceDataFixtures#16]
It seems that [Ocramius/ProxyManager](https://github.com/Ocramius/ProxyManager) does not support final classes. As such some services needs to be reworked to be able to be declared as lazy.

@Ocramius sorry to annoy again, can you just confirm this is a desired behaviour?

**Comment by Ocramius** [comment]
Yeah, ProxyManager currently does not support proxying final classes. It
may do so in future versions, as a post-install composer step.

**Comment by theofidry** [comment]
@Ocramius that would be really cool indeed. I don't really like the idea to have to change the way a service is designed just because in a certain context it is registered in a special way. Although I guess there is technical challenges to do so

**Comment by Ocramius** [comment]
In theory, I could proxy the interface. Zend\ServiceManager supports that,
but no idea about other service containers.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by theofidry** [comment]
So in Zend this is bypassed by fixing that at the integration level? To be honest I would expect it to be done at the library level.

**Comment by Ocramius** [comment]
The ProxyManager just generates proxies. What kind of proxy you want, and
for which class or interface, is for you to decide.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by theofidry** [comment]
True, although you are generating a proxy for a class/interface only, so if your final class implements two interfaces, how do you do?

**Comment by Ocramius** [comment]
You'd have to create an intermediate interface, then implement that one in
your final class. Can probably also compose multiple interfaces, but please
open an issue for that :)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by theofidry** [comment]
@Ocramius damn, whenever I follow you advices, even if they do feel right, I always end up in trouble :P See the complexity of alice and how I'll get gutted from https://github.com/symfony/symfony/issues/20392 💀
