### ISSUE TITLE
1.3.2: Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by VincentLanglet** [theofidry/AliceDataFixtures#164]
I have a weird behavior with `1.3.2` that I don't have with `1.3.0`. @benja-M-1 @theofidry 

When I tried to load my fixture I get
```
In IdentityGenerator.php line 61:
                                                              
  Maximum function nesting level of '256' reached, aborting!                                                          
```

But it only occur on CircleCi.

I don't have the issue locally ; and I don't have the issue on github actions.

Any idea why ?

**Comment by theofidry** [comment]
It was reported in https://github.com/theofidry/AliceDataFixtures/issues/163 as well

/cc @bricejulia

>I don't have the issue locally ; and I don't have the issue on github actions.

Either xdebug and/or max nested level setting

**Comment by VincentLanglet** [comment]
Will be fixed by https://github.com/theofidry/AliceDataFixtures/pull/165
