### ISSUE TITLE
"nelmio\alice":"^3.5" doesn't support PHP8

### ISSUE THREAD

**Issue by fvhde** [theofidry/AliceDataFixtures#172]
the nelmio\alice version which supports PHP8 is 3.8. In the composer.json we have ^3.5 which drive me to : 
```
    - nelmio/alice[v3.5.0, ..., v3.6.0] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - nelmio/alice[v3.7.0, ..., 3.7.4] require php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires fzaninotto/faker dev-master -> satisfiable by fzaninotto/faker[dev-master].
    - Root composer.json requires theofidry/alice-data-fixtures ^1.4 -> satisfiable by theofidry/alice-data-fixtures[1.4.0, 1.x-dev (alias of dev-master)].
```

**Comment by alexislefebvre** [comment]
What is the question?

You should be able to upgrade like this:

```bash
composer require --dev theofidry/alice-data-fixtures:^3.8
```

**Comment by fvhde** [comment]
When i try to install your package ^1.4, i have an error concerning nelmio\alice. I saw in your `composer.json` that you require nelmio\alice ^3.5 . This version of nelmio\alice seems to not support PHP8 so i'm unable to install your package due to dependency error.

**Comment by alexislefebvre** [comment]
Sorry, I misrode the requirement, please try this:

```
composer require --dev nelmio/alice:^3.8
```

And share the errors if there are.

**Comment by fvhde** [comment]
Thanks it seems that it resolved the problem.
