### ISSUE TITLE
Loader implementation example

### ISSUE THREAD

**Issue by studiomado** [theofidry/AliceDataFixtures#18]
Hi,
can you show a custom loader implementation with Symfony+Doctrine?
Thanks

**Comment by theofidry** [comment]
@studiomado what are you looking for? There is actually a few loader examples [here](https://github.com/theofidry/AliceDataFixtures/tree/master/src/Loader).

**Comment by studiomado** [comment]
Where do I put the file? 
I have to register as a service?

**Comment by theofidry** [comment]
If you are using Symfony, the existing loaders are already registered in `FidryAliceDataFixturesBundle`, you can find them [here](https://github.com/theofidry/AliceDataFixtures/tree/master/src/Bridge/Symfony/Resources/config).

If you want to have a custom one for some reason, yes you must 1. make sure your class implements the loader and 2. declare it as a service. As for *where* it matters little, so where it makes sense in your app or for you :) I personally would put one in `src/Alice/DataFixtures/Loader/` but I'm the kind not to follow the traditional file structure of a Symfony application. So maybe `src/AppBundle/Alice/DataFixtures/Loader/`? Up to you really.
