### ISSUE TITLE
Relationships are empty during tests after loading the fixtures

### ISSUE THREAD

**Issue by CedCannes** [theofidry/AliceDataFixtures#185]
Steps to reproduce

I prepared a [repo](https://github.com/CedCannes/sf_bug_collections_empty_during_tests_with_fixtures) to show all this
1.Create entities in OneToMany relationship (here Board and Lane)
2.Create yml files of fixtures with 1 Board that has 4 Lanes
3.Write a test that loads the fixtures and checks that there is a collection of 4 lanes in board
Expected result

    The board should have 4 lanes

Actual result

    Failed asserting that actual size 0 matches expected size 4. Collection $board->getLanes() is empty

To make it work have to clear the entity manager after loading the fixtures files and the tests pass normally.

`static::getContainer()->get('doctrine')->getManager()->clear();`

**Comment by alexislefebvre** [comment]
I think I had a similar issue with a cache from Doctrine.

Try to call `refresh($board);` before calling `assertCount`, `refresh()` is provided by `ObjectManager`.

**Comment by theofidry** [comment]
Could you please try again with 1.5.0?
