### ISSUE TITLE
[Doctrine] Support for disabling ID generators if ID provided in fixture

### ISSUE THREAD

**Issue by dkarlovi** [theofidry/AliceDataFixtures#40]
If you have a Doctrine custom PK generator like [ramsey/uuid-doctrine](https://github.com/ramsey/uuid-doctrine), you can't set that auto-PK from fixture because [it's getting overwritten by Doctrine](http://stackoverflow.com/questions/5301285/explicitly-set-id-with-doctrine-when-using-auto-strategy) after you've set it.

If provided in fixture, It would be nice to disable Doctrine auto-PK generator and use the one provided from fixture.

**Comment by theofidry** [comment]
I'm not really sure of what you are suggesting: how should the library detect your custom auto-PK generators? More importantly, maybe it doesn't make sense to disable it for some people or people may have their own generators that should not be disabled.

I think decorating the persister or the loader in your case to do the manipulation you want to do would be better.

**Comment by dkarlovi** [comment]
@theofidry currently, if you have a custom PK generator, but specify the PK in the fixture, it will NOT be correctly saved (as Doctrine will overwrite it, as linked above).

My proposal is: if you specify a value for the PK, library should try to get it stored. This means, if you specify a value for a PK, it should temporarily disable the custom PK generator for that specific entity instance.

If it doesn't make sense to disable the generator, people will just not specify a PK value in the fixture, in that case everything works exactly as it does now.

**Comment by blaues0cke** [comment]
@dkarlovi Maybe this is an workaround for you, too: https://stackoverflow.com/questions/36942619/can-i-override-auto-increment-id-with-alice-fixtures/43119749#43119749

**Comment by theofidry** [comment]
I think that's a good way to do it. I'm not convinced this should be done in alice core to be honest. decorating the command to do specific stuff is the way to go. So I think we should simply add an entry in the doc for it

**Comment by dkarlovi** [comment]
My use case is: I use FOS oAuth2 server bundle (building an API app, API Platform based) with Ramsey UUID Doctrine type as PK. When bootstrapping the database for development env, I run development fixtures which create a oAuth client entry. Its PK is a part of the client's public ID which is used directly when authenticating with the oAuth2 server for an access token.

What I'd like to do is have development fixtures automatically create clients for Swagger UI (provided by app), Postman or other clients, I can then provide exact configuration in app's documentation for new developers to use instead of having a list of things to do to get it working.

I understand it's probably an edge case, but will probably come up again with more users of the lib. At least consider throwing an exception if this case is triggered. Thanks.

**Comment by theofidry** [comment]
@dkarlovi I would simply advise to not use an auto-generated UUID. IMO that kind of defeat the purpose of using an UUID

**Comment by dkarlovi** [comment]
@theofidry that's the point of this issue: I want my app to use autogen UUIDs as PKs everywhere, but (only in this specific case) the fact I can't set it manually from fixture is the problem.

> IMO that kind of defeat the purpose of using an UUID

What does?

**Comment by theofidry** [comment]
>I want my app to use autogen UUIDs as PKs everywhere, but (only in this specific case) the fact I can't set it manually from fixture is the problem.

Maybe it would be possible to add another loader which disable them by manipulating the metadata to make things easier.

>What does?

One advantage of UUIDs is that it allows you to assign an ID to manipulate your objects and relationships with confidence without having to hit the database layer. Which is something you cannot do with an auto-generated interger as if you take an arbitrary integer, you have zero guarantee of it to be available when you are going to persist your entity.

**Comment by dkarlovi** [comment]
> Maybe it would be possible to add another loader which disable them by manipulating the metadata to make things easier.

Would that be done by the lib or userland? Can you give me a rough outline how it would work / be used?

> UUID

UUID was chosen here exclusively to solve some current and future issues for the persistence layer, PKs are otherwise completely opaque to the whole application, except for one very simple exception. :)

**Comment by theofidry** [comment]
>Would that be done by the lib or userland?

I was thinking the lib, roughly creating a loader implementing [LoaderInterface](https://github.com/theofidry/AliceDataFixtures/blob/master/src/LoaderInterface.php), which decorates the current loader and manipulate the metadata before delegating the loading to the decorated loader

**Comment by dkarlovi** [comment]
That sounds reasonable. Would the user need to specify the loader per fixture, how would that be configured?

**Comment by theofidry** [comment]
>Would the user need to specify the loader per fixture

I would rather not. This would require to change a lot more things and I'm not sure it's really a wanted feature.

I would rather add an entry in the bundle configuration which then can be passed down to the loader constructor

**Comment by dkarlovi** [comment]
Sounds good, let me know if you need something tested here.

**Comment by theofidry** [comment]
Thanks :) But I'm prefer to warn that I'm really not sure when I'll find time to allocate on this. Life has been very busy for the last few months.

**Comment by dkarlovi** [comment]
I can always: send a PR, create these fixtures some other way, etc. Don't worry about it, thanks for the heads up. :+1:

**Comment by theofidry** [comment]
That would be much appreciated :)

**Comment by dkarlovi** [comment]
@theofidry could you give me a few pointers how one would implement this? I'm looking at the code currently, trying to figure out how to do it. Found a new use-case BTW: Behat tests for GET with API Platform.

My use case is as follows:

**Fixture:**
```yaml
# image-cfbdd352-a847-11e7-abc4-cec278b6b50a.yml
AppBundle\Entity\User:
    user_0:
        email (unique): <email()>
        username (unique): <username()>
        password: <password()>

ImageBundle\Entity\Image:
    test_0:
        id: cfbdd352-a847-11e7-abc4-cec278b6b50a
        name: <name()>
        created_by: "@user0"
        updated_by: "@user0"
```

**Feature:**
```gherkin
    Scenario: Fetching an existing image
        Given the fixture file "@ImageBundle:image-cfbdd352-a847-11e7-abc4-cec278b6b50a.yml" is loaded
        When I send a "GET" request to "/api/images/cfbdd352-a847-11e7-abc4-cec278b6b50a"
        Then ...
```

You said earlier:

> roughly creating a loader implementing LoaderInterface, which decorates the current loader

Being `fidry_alice_data_fixtures.doctrine.persister_loader`?

> and manipulate the metadata before delegating the loading to the decorated loader

Metadata being Doctrine's metadata for the entity? Basically:

1) decorate `Loader` with `DecoratedLoader`
2) `load()`
3) `DecoratedLoader::load()` disables Doctrine ID generator
4) `DecoratedLoader::load()` runs `Loader::load()`
5) `DecoratedLoader::load()` enabled Doctrine ID generator

Something like that?

**Comment by dkarlovi** [comment]
Totally missed the link by @blaues0cke. :( That might help me quite a bit.

**Comment by theofidry** [comment]
Sure. In pseudo-code, I imagine something along the lines of:

```php
class DoctrineIdGeneratorLoader implements LoaderInterface {
  private $decoratedLoader;

  function load($objects, ...$args): {
    $metadatas = $this->retrieveMetadatas($objects); // Collect metadata of the entities for which the generator must be disabled
    // disable all the generators
    $this->decoratedLoader->load($objects, ...$args);
    // enable back all the generators
  }
}
```

which is quite close from the steps you just gave :)

**Comment by theofidry** [comment]
Coming back to this: I'm not sure this is desirable either as if you implement a loader for it in the core, it would be to apply it to _all_ the entities which is certainly not what you want. Instead it would be better to just add a doc entry to easily be able to implement your own whenever you need it to.

**Comment by dkarlovi** [comment]
@theofidry your provided solution doesn't quite match the desired behaviour.

Namely, in your example, `AssignedGenerator` is assigned to **any** instance of `Dummy`, regardless of changes.

My problem would require to apply the `AssignedGenerator` to instance of any entity, but **only if the identifier was specified in fixture**. If it was not, everything should work exactly as it currently does (namely, triggering whatever generator was set, if any).

I have something semi-working by overriding the persistor (which gets the complete entity instance and knows if an identifier was set), getting some weird errors which I'll fix tomorrow. As it's possible to get this behaviour (and it only triggers if quite preconditions are met) only by decorating one class, I stil lthink it's worth having this in the core lib, even hidden behind a feature flag.

**Comment by theofidry** [comment]
I'm curious to know how you did it. I don't have a definite opinion on the topic, I'm just not always in favour of having too many feature flags when a little doc entry for those special edge cases hard to generalise does the job. But depending on what you have I may change my mind :)

**Comment by dkarlovi** [comment]
That sounds fair enough. :)

So, I have [this](https://gist.github.com/dkarlovi/02152bb5d8bbfb1171a3789327edfa3c) and it almost works, I'm getting some weird error I need to work out.

But basically, this works (or, for now, should work :sob: ) as expected: if you're using Doctrine and you're setting an ID generator, but you've set an ID from the fixture, the generator is overridden to assure your ID  gets set.

The condition is very specific and, IMO, it actually improves the behaviour overall as it applies the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment): you're getting behaviour you'd actually expect, even if it's not technically correct.

**Comment by theofidry** [comment]
I'm cool with that solution 👍

**Comment by dkarlovi** [comment]
Cool, how do we proceed? Do we document this or ship the class to decorate the persister service yourself with?

**Comment by theofidry** [comment]
Let's just ship it and remove the doc entry which would then become obsolete

**Comment by dkarlovi** [comment]
Would need to update the docs how to decorate, similar to private property accessor too.

OK, will attach a PR this week. Thanks!

**Comment by theofidry** [comment]
There is already [this doc entry](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#custom-accessor) for the property accessor, or are you thinking of something else?

**Comment by dkarlovi** [comment]
Upvoting your own comment, I like your style. :+1: 

No, I was thinking **similar** to that. So, we ship the class and update the docs to:
1. remove obsolete reference which closed this issue
2. add an explanation on how to do use the shipped class

Or did you have some other idea?

**Comment by theofidry** [comment]
>Upvoting your own comment, I like your style. 👍

Wrong comment :P

>add an explanation on how to do use the shipped class

I was thinking of enabling it by default, so there is not much need to document it's usage

**Comment by dkarlovi** [comment]
> I was thinking of enabling it by default, so there is not much need to document it's usage

OK, even better. I'll have a PR this week. Can you re-open this issue until it's done?

**Comment by dkarlovi** [comment]
@theofidry do you think this should be a decorator class or do we do it directly in `Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister`?
