### ISSUE TITLE
PurgLoader breaks load interface

### ISSUE THREAD

**Issue by hashnz** [theofidry/AliceDataFixtures#43]
The loaders decorate other loaders and call the load method, however the PurgeLoader::load signature differs from the interface meaning the purge mode is not able to be set on a decorated loader:

    $loader = new PurgerLoader($loader, $purger);
    $loader = new FileResolverLoader($loader, new KernelFileResolver($kernel));

https://github.com/theofidry/AliceDataFixtures/blob/master/src/Loader/PurgerLoader.php#L58
https://github.com/theofidry/AliceDataFixtures/blob/master/src/LoaderInterface.php#L34

**Comment by theofidry** [comment]
That will be handled in https://github.com/theofidry/AliceDataFixtures/pull/42. I just need to test it on HautelookAliceBundle as well

**Comment by theofidry** [comment]
Closing as the work is done in this library, I need to update HautelookAliceBundle accordingly
