### ISSUE TITLE
Installation breaks usage of doctrine:generate:entities

### ISSUE THREAD

**Issue by scuben** [theofidry/AliceDataFixtures#53]
After installing this library I cannot use `doctrine:generate:entities` because the constructor of `Fidry\AliceDataFixtures\Bridge\Doctrine\Persister` is calculating the ClassMetadata trough Doctrine. Now this is raising an Exceptions when I add new columns in my XML Mapping but do not yet have them in my Entity.

**Comment by theofidry** [comment]
I see, I guess we could move the class metadata calculation out of the constructor [here](https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php#L42).

**Comment by scuben** [comment]
Yes I think so too. I just "fixed" it for me to dedicate a special environment to the fixtures loading.
