### ISSUE TITLE
Purge with truncate does not work

### ISSUE THREAD

**Issue by scuben** [theofidry/AliceDataFixtures#54]
Specifying `--purge-with-truncate` still does a normal `DELETE FROM ...`.

I think the critical code is in [PurgerLoader.php](https://github.com/theofidry/AliceDataFixtures/blob/master/src/Loader/PurgerLoader.php#L60) because in [DoctrineOrmLoader.php](https://github.com/hautelook/AliceBundle/blob/master/src/Loader/DoctrineOrmLoader.php#L174) the parameter `$purgeMode` is not given.

**Comment by theofidry** [comment]
Re-opened on the proper repository
