### ISSUE TITLE
Allow to disable foreign keys

### ISSUE THREAD

**Issue by theofidry** [theofidry/AliceDataFixtures#63]
From #32, we could add it to the Purge in the `purge()` method to get access to the connection and disable the foreign key checks before running the actual purge.

As this may not be the desirable default behaviour, we could add an option in the config passed to the purger factory.

/cc @robertfausk

**Comment by robertfausk** [comment]
I just created a PR in doctrine/data-fixtures https://github.com/doctrine/data-fixtures/pull/272.

If it is not going to be merged then I will provide a PR for this in AliceDataFixtures.

**Comment by theofidry** [comment]
@robertfausk maybe a better idea would be to completely ditch the DataFixtures purge and have our own here. As we would disable the foreign key check, it would also be much simpler as there is no need to sort depending of the associations and co. to know what to truncate first, we can just truncate everything. This would also allow us to ditch the `doctrine/data-fixtures` as a requirement.

WDYT?

**Comment by theofidry** [comment]
Thinking about this again, it doesn't make much sense as the issue is the order. The order is true irrelevant with a TRUNCATE, but it is still for the DELETE with is the default.

**Comment by robertfausk** [comment]
Coolio! I think its a good approach to have a solution for AliceDataFixtures as long as there is no decision in doctrine/data-fixtures#272.
