### ISSUE TITLE
Context Error Exception : Undefined Offset -5

### ISSUE THREAD

**Issue by mngkvn** [theofidry/AliceDataFixtures#72]
On windows, when I run doctrine:load:fixtures and proceed to purge the database, it gives me that error but when I run it on my Mac, everything runs fine.

**Comment by theofidry** [comment]
Unfortunately I don't have a windows at home and I'm not very experienced with AppVeyor either, so I can't really look at it on my side :/

**Comment by theofidry** [comment]
Closing as there is unfortunately not much I can do. I'm happy to add windows support but it requires someone to be willing to set up and add AppVeyor + doing the necessary changes to fix it
