### ISSUE TITLE
Is MongoDB Supported with doctrine ODM?

### ISSUE THREAD

**Issue by luishdez** [theofidry/AliceDataFixtures#77]
I see there are some mongodb tests but there is no documentation regarding. 

Is doctrine Odm + symfony already supported ?

**Comment by luishdez** [comment]
OK I saw there is support only the doc is missing.

**Comment by theofidry** [comment]
Let's re-open this as the doc is indeed missing :) If you ever get a chance to PRs are welcome!

**Comment by bmeynell** [comment]
> Is MongoDB Supported with doctrine ODM?

No, as far as I can tell:
- https://github.com/theofidry/AliceDataFixtures/issues/122
- https://github.com/hautelook/AliceBundle/issues/457
- https://github.com/hautelook/AliceBundle/issues/324
- https://github.com/hautelook/AliceBundle/pull/440
