### ISSUE TITLE
How to make it works in Symfony 4?

### ISSUE THREAD

**Issue by ajielee** [theofidry/AliceDataFixtures#86]
Hello there, I've installed this bundle in a Symfony 4 project with this command:

```
composer require --dev theofidry/alice-data-fixtures doctrine/orm:^2.5 doctrine/data-fixtures
```

And then I added these two lines in `bundles.php`:

```
return [
    ...
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true],
];
```

But it still doesn't work, as I use `php bin/console` to check the command list, there is no any thing about fixture.

Could someone tell me is there any step I've missed? Thank you.
Ps: I think the `README.md` need to be updated. As this bundle supports Symfony 4.0+, but the introduction of installation doesn't fit the new framework structure any more.

**Comment by petegore** [comment]
Hi,

I was wondering the same today and I succeed creating this file to load my fixtures using the command `doctrine:fixtures:load` : 

```php
<?php

namespace App\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class AppFixtures extends Fixture implements ContainerAwareInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    public function load(ObjectManager $om)
    {
        $fixturesFiles = [
            __DIR__.'/FixtureEntity1.yaml',
            __DIR__.'/FixtureEntity2.yaml'
        ];
        $loader = $this->container->get('fidry_alice_data_fixtures.loader.doctrine');

        return $loader->load($fixturesFiles);
    }
}
```

**Comment by theofidry** [comment]
Indeed, there is not load fixture command in this library. This library is to try to remain as small as possible so only provides a way to persist the fixtures, nothing more.

Having a console command implies have a strategy to find the fixture files you want to load, this is done by a HautelookAliceBundle.

Hope that helps :)

**Comment by ajielee** [comment]
@theofidry I've tried `HautelookAliceBundle`, but come across this problem: https://github.com/hautelook/AliceBundle/issues/386

**Comment by theofidry** [comment]
Yes the issue is still ongoing, but did you see [this comment](https://github.com/hautelook/AliceBundle/issues/386#issuecomment-355740652)? It just means installing the bundle with flex is a bit awkward at the moment, but you can do without

**Comment by ajielee** [comment]
@theofidry Thank you for your reply, I've downgraded the Symfony version to 3.3, there are still so many inconveniences while using Symfony 4.0.

**Comment by theofidry** [comment]
It's worth mentioning that it's just the default install with Flex that is causing an issue, you can still install a bundle without flex and it's not specific to Symfony 4.0 either

**Comment by spacetraveller** [comment]
Hi, how do we install without flex ? Symfony 4.0 really does still have the above mentioned issue when attempting to install this, and the solutions offered currently add more confusion.

**Comment by ajielee** [comment]
As @spacetraveller said, the problem still exists, so I reopen this issue and hope that there will be one proper solution.

**Comment by spacetraveller** [comment]
I have found a workaround, and that is to say "no" to the recipe offer when running through the 'require'.

  -  WARNING  hautelook/alice-bundle (>=1.4): From github.com/symfony/recipes-contrib:master
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/master/hautelook/alice-bundle/1.4

    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n): n
Executing script cache:clear [OK]
