### ISSUE TITLE
How use addXXX() methods instead setXXX() methods in fixtures load?

### ISSUE THREAD

**Issue by nickicool** [theofidry/AliceDataFixtures#92]
Hi! 

I use SF4 and your bundle. I have a manytomany relationship between 2 entity: Image and Gallery. Doctrine requires the `addImage()` and `addGallery()` methods to work. And for your bundle to work, in entities need the `setImage()` and `setGallery()` methods that neither Doctrine nor me in my code needs. 

Is there a way to force your bundle to use addImage() and addGallery() instead of setImage() and setGallery()?

Now for work Doctrine and fixtures i need do some this:

    // if I delete this method, the fixtures do not work - shows an error
    public function setGallery(Gallery $gallery)
    {
        // Everything works well even with an empty method, the main thing - that it was
    }

    public function addGallery(Gallery $gallery)
    {
        if ($this->galleries->contains($gallery)) {
            return;
        }
        $this->galleries->add($gallery);
        $gallery->addImage($this);
    }

I'm just learning how to work with SF and don't know how to solve this complication of the code. Maybe this issue isn't about your bundle. Just tell me what to do or where else to ask for help.

Sorry for my bad English!

**Comment by theofidry** [comment]
Hi,

This should work with `addImage` and `addGallery` although IIRC the Symfony Property Accessor requires the `remove*()` method as well to detect the `add*()`. Otherwise you can always use a [custom accessor](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#custom-accessor) to do whatever you want

**Comment by nickicool** [comment]
Maybe someone will tell where to get needed "custom accessor" for the manytomany properties? Or an example of how to write? 

Because it's too complicated for me... I won't be able to do so. 

I am sure that this is not a unique situation, many people use "nelmio/alice" to fixtures manytomany relationship.

**Comment by theofidry** [comment]
Did you check the link? You have two real life examples linked in it and how the service should be registered in Symfony

**Comment by ogizanagi** [comment]
@nickicool : You should have a look at https://symfony.com/doc/current/service_container/service_decoration.html to understand a bit more what this code excerpt implies :)

_`TL;DR`_: the `*.inner` argument you see is the service you are decorating, whose name is generated from your decorated service name, suffixed by `.inner`. So if you name your service `Nelmio\Alice\PropertyAccess\ReflectionPropertyAccessor`, the argument to use is `Nelmio\Alice\PropertyAccess\ReflectionPropertyAccessor.inner` 😉

Or from the docs:
> The generated inner id is based on the id of the decorator service (App\DecoratingMailer here), not of the decorated service (App\Mailer here). You can control the inner service name via the decoration_inner_name option:

**Comment by nickicool** [comment]
@ogizanagi thanks for answer and help! I'm really trying to figure out how it works and what to do. But until all very and very difficult. I haven't dug that deep yet. Most likely I'll write another stupid thought, but...

I create class that will decorate `NativeLoader`:

    namespace App\Fixtures;
    use Nelmio\Alice\Loader\NativeLoader;
    use Nelmio\Alice\PropertyAccess\ReflectionPropertyAccessor;
    use Symfony\Component\PropertyAccess\PropertyAccessorInterface;
    
    class ReflectionPropertyLoader extends NativeLoader
    {
        protected function createPropertyAccessor(): PropertyAccessorInterface
        {
            return new ReflectionPropertyAccessor(parent::createPropertyAccessor());
        }
    }

What methods do I need to override in this class so that some properties use add*() methods instead of set*()?

And in `services.yaml` I add service:

    App\Fixtures\ReflectionPropertyLoader:
        public: false
        decorates: nelmio_alice.property_accessor
        decoration_priority: -10
        arguments: ['Nelmio\Alice\PropertyAccess\ReflectionPropertyAccessor.inner']

And now is show errors:
> [error] Error thrown while running command "doctrine:fixtures:load". Message: "Argument 1 passed to Nelmio\Alice\Loader\NativeLoader::__construct() must be an instance of Faker\Generator or null, string given, called in D:\...\dev\ContainerOf9M6TJ\getNelmioAlice_DataLoaderService.php on line 184"
> [critical] Type error: Argument 1 passed to Nelmio\Alice\Loader\NativeLoader::__construct() must be an instance of Faker\Generator or null, string given, called in D:\...\dev\ContainerOf9M6TJ\getNelmioAlice_DataLoaderService.php on line 184

**Comment by nickicool** [comment]
Yeah, that's my mistake. Everything was easy - I was wrong yaml file fixtures. Where should be the property of the plural "galleries:" was "gallery:". Similar to the "images:"property. 

Surprisingly, it all worked as long as I did not pay attention to "unnecessary" methods. It is difficult while there is a training. 

Thank you for the great bandle! Hopefully not much blew your brain my noob.
