### ISSUE TITLE
Add ProcessorInterface::process method

### ISSUE THREAD

**Issue by Soullivaneuh** [theofidry/AliceDataFixtures#93]
Same issue as https://github.com/nelmio/alice/issues/318 which was not resolved because not related to alice v3 anymore.

I have this following method:

```php
public function saveDomain(PowerDNSDomain $domain, ?string $ipV4 = null, ?string $ipV6 = null, bool $checkDNS = true): void
{
    $this->persist($domain);
    $this->flush();

    $this->generateSOA($domain);
    $this->generateNS($domain);
    $this->generateBasicEntries($domain, $ipV4, $ipV6, $checkDNS);
}
```

For some reasons, I have to flush the domain before generating new entries and save them again.

I would need to have a `process` method to avoid the use of `postProcess` and the twice doctrine flushing.

Is that something reasonable to you?

Regards.

**Comment by Soullivaneuh** [comment]
Maybe. But the result will be the same AFAIK : Double persisting.

The goal of the `process` method is to let the user define the custom way to persist the entity.

**Comment by theofidry** [comment]
As stated, I think there is a difference of expectations:

- preProcess: let you manipulate objects _before_ being persisted
- persist: which can be customised by a custom persister
- postProcess: let you manipulate objects _after_ being persisted

So I'll be closing this for now unless something is not clear, in which case feel free to ping me again either here or on Slack
